/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-21 08:43:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1686617076349L));
    _jspx_dependants.put("jar:file:/D:/pcj/06_springWork/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/pcj/06_springWork/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/D:/pcj/06_springWork/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BUCKET LIST</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/swiper.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/swiper.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"hd center12\">\r\n");
      out.write("            <a href=\"\" class=\"menuBtn\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span class=\"center\"></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <h1><a href=\"\"><img src=\"resources/img/logo.png\" alt=\"\"></a></h1>\r\n");
      out.write("            <ul class=\"rightMenu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/member/login.jsp\">LOGIN</a></li>\r\n");
      out.write("                <li><a href=\"\">JOIN</a></li>\r\n");
      out.write("            <!-- 수정 1 test -->\r\n");
      out.write("                <!-- 로그인했을 때 로그인, 회원가입 사라지고 노출되는 버튼 -->\r\n");
      out.write("                <!-- <li><a href=\"\">LOGOUT</a></li> -->\r\n");
      out.write("                <!-- <li><a href=\"\">MYPAGE</a></li> -->\r\n");
      out.write("\r\n");
      out.write("                <!-- 로그인 안한 상태에서 누르면 로그인 안내멘트 뜨고 로그인 페이지로 이동 -->\r\n");
      out.write("                <li><a href=\"\">MY BOOKING</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- 호스트 아이디로 로그인했을 때 노출되는 버튼 -->\r\n");
      out.write("                <!-- <li><a href=\"\" class=\"plusBtn\">HOST PAGE</a></li> -->\r\n");
      out.write("    \r\n");
      out.write("                <!-- 관리자 아이디로 로그인했을 때 노출되는 버튼 -->\r\n");
      out.write("                <!-- <li><a href=\"\" class=\"plusBtn\">ADMIN PAGE</a></li> -->\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"\" class=\"reserBtn\">RESERVATION</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"fkHeader\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mainVisual cf\">\r\n");
      out.write("        <div class=\"imgBn swiper-container\">\r\n");
      out.write("            <ul class=\"main_banner swiper-wrapper\">\r\n");
      out.write("                <li class=\"swiper-slide imgArea\" style=\"background-image: url(resources/img/main_bn01.jpg);\"></li>\r\n");
      out.write("                <li class=\"swiper-slide imgArea\" style=\"background-image: url(resources/img/main_bn02.jpg);\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"swiper-pagination\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>    \r\n");
      out.write("            var swiper = new Swiper('.swiper-container', {\r\n");
      out.write("                  autoplay: {\r\n");
      out.write("                    delay: 3000,\r\n");
      out.write("                },\r\n");
      out.write("                effect : 'fade',\r\n");
      out.write("                speed : 1500,\r\n");
      out.write("                // pagination: {				\r\n");
      out.write("                //     el: '.swiper-pagination',\r\n");
      out.write("                //     clickable: true,\r\n");
      out.write("                // },\r\n");
      out.write("            });			    \r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"\" class=\"reservation\">\r\n");
      out.write("            <div class=\"area\">\r\n");
      out.write("                <p class=\"reTxt\">AREA</p>\r\n");
      out.write("                <input type=\"text\" placeholder=\"지역 선택\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"date\">\r\n");
      out.write("                <p class=\"reTxt\">CHECK IN/OUT</p>\r\n");
      out.write("                <input type=\"text\" placeholder=\"날짜를 선택해주세요.\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"num\">\r\n");
      out.write("                <p class=\"reTxt\">PERSONS</p>\r\n");
      out.write("                <input type=\"number\" value=\"22\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\" value=\"SEARCH\" class=\"searchBtn\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bestWrap\">\r\n");
      out.write("        <div class=\"center12\">\r\n");
      out.write("            <h3 class=\"mainTit serif\">Best Destination</h3>\r\n");
      out.write("            <p class=\"mainTxt\">베스트 여행지 어쩌고 저쩌고</p>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"desList\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"imgArea\"><div class=\"img\" style=\"background-image: url(resources/img/local01.jpg);\"></div></div>\r\n");
      out.write("                        <p class=\"tit\">서울</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"imgArea\"><div class=\"img\" style=\"background-image: url(resources/img/local02.jpg);\"></div></div>\r\n");
      out.write("                        <p class=\"tit\">제주</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"imgArea\"><div class=\"img\" style=\"background-image: url(resources/img/local03.jpg);\"></div></div>\r\n");
      out.write("                        <p class=\"tit\">부산</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"imgArea\"><div class=\"img\" style=\"background-image: url(resources/img/local04.jpg);\"></div></div>\r\n");
      out.write("                        <p class=\"tit\">인천</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"imgArea\"><div class=\"img\" style=\"background-image: url(resources/img/local05.jpg);\"></div></div>\r\n");
      out.write("                        <p class=\"tit\">강원</p>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"themeWrap center12\">\r\n");
      out.write("        <ul class=\"themeTab\">\r\n");
      out.write("            <li><a href=\"\">커플여행</a></li>\r\n");
      out.write("            <li><a href=\"\">가족여행</a></li>\r\n");
      out.write("            <li><a href=\"\">MT</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"accList\">\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room01.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like_ac.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name ellipsis\">서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room02.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room03.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room04.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name ellipsis\">서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room05.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">제주</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room06.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>100,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bestReviewWrap\">\r\n");
      out.write("        <h3 class=\"mainTit serif\">Best Accommodations</h3>\r\n");
      out.write("        <p class=\"mainTxt\">평점 높은 숙소들 어쩌고 저쩌고</p>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"accList center12\">\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room04.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like_ac.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">서울</p>\r\n");
      out.write("                <p class=\"name ellipsis\">서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스 서울라이트 펜트하우스</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>120,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room05.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">부산</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>99,990</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"listLi\" onclick=\"location.href=''\">\r\n");
      out.write("                <div class=\"imgArea\" style=\"background-image: url(resources/img/room06.jpg);\">\r\n");
      out.write("                    <img src=\"resources/img/ratio43.png\" alt=\"\" class=\"ratio\">\r\n");
      out.write("                    <a href=\"\" class=\"heartBtn\"><img src=\"resources/img/like.png\" alt=\"\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"local\">인천</p>\r\n");
      out.write("                <p class=\"name\">숙소이름 샬라샬라</p>\r\n");
      out.write("                <ul class=\"detail\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/like_line.png\" alt=\"\">\r\n");
      out.write("                        <p>10</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"resources/img/star.png\" alt=\"\">\r\n");
      out.write("                        <p>4.9</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"price\">1박 <strong>70,000</strong>원~</p>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"center12\">\r\n");
      out.write("            <p class=\"ft_txt\">\r\n");
      out.write("                <span><strong class=\"name\">BUCKET LIST</strong></span>\r\n");
      out.write("                <span><strong>대표이사</strong> 홍길동</span>\r\n");
      out.write("                <span><strong>주소</strong> 주소적어어어어어어어어어어어어어어엉</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"ft_txt\">\r\n");
      out.write("                <span><strong>전화번호</strong> 02-111-1111</span>\r\n");
      out.write("                <span><strong>팩스번호</strong> 02-111-2222</span>\r\n");
      out.write("                <span><strong>사업자등록번호</strong> 111-22-33333</span>\r\n");
      out.write("                <span><strong>이메일</strong> bucketlist@bk.co.kr</span>\r\n");
      out.write("                <span><strong>개인정보보호책임자</strong> 홍길동</span>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"copy\">Copyright © BUCKET LIST All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("    <a href=\"\" class=\"topBtn\"><img src=\"resources/img/arr_top.png\" alt=\"\"></a>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(window).scroll(function(){\r\n");
      out.write("            if ($(this).scrollTop() > 300){\r\n");
      out.write("                $('.topBtn').fadeIn();\r\n");
      out.write("            } else{\r\n");
      out.write("                $('.topBtn').fadeOut();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $('.topBtn').click(function(){\r\n");
      out.write("            $('html, body').animate({scrollTop:0},400);\r\n");
      out.write("            return false;\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
